// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBff716o3wBV_Vh3wEDZ8MCxuuNwWrGnjM',
    appId: '1:796677571165:web:cf17451e888f22f18f43b4',
    messagingSenderId: '796677571165',
    projectId: 'dukanji2-a60e8',
    authDomain: 'dukanji2-a60e8.firebaseapp.com',
    storageBucket: 'dukanji2-a60e8.appspot.com',
    measurementId: 'G-FYWE05JPSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdrT4KNoTgY0I9DV8qvKYhcrkC9jGesa0',
    appId: '1:796677571165:android:096d027453218a848f43b4',
    messagingSenderId: '796677571165',
    projectId: 'dukanji2-a60e8',
    storageBucket: 'dukanji2-a60e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLUO6nlgwHEvE4R60Y_Dr89AYolgRnndc',
    appId: '1:796677571165:ios:2dd2f152019571a08f43b4',
    messagingSenderId: '796677571165',
    projectId: 'dukanji2-a60e8',
    storageBucket: 'dukanji2-a60e8.appspot.com',
    iosBundleId: 'com.example.dukanji2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLUO6nlgwHEvE4R60Y_Dr89AYolgRnndc',
    appId: '1:796677571165:ios:2dd2f152019571a08f43b4',
    messagingSenderId: '796677571165',
    projectId: 'dukanji2-a60e8',
    storageBucket: 'dukanji2-a60e8.appspot.com',
    iosBundleId: 'com.example.dukanji2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBff716o3wBV_Vh3wEDZ8MCxuuNwWrGnjM',
    appId: '1:796677571165:web:8cbae5707ba177d58f43b4',
    messagingSenderId: '796677571165',
    projectId: 'dukanji2-a60e8',
    authDomain: 'dukanji2-a60e8.firebaseapp.com',
    storageBucket: 'dukanji2-a60e8.appspot.com',
    measurementId: 'G-0PER2SNW4L',
  );
}
